### PR TITLE
Add Swipe down threshold

### PR DESCRIPTION
**Pull request by wack17s**

### CODE REVIEW

**Comment by wack17s** [comment]
@ascoders 
Seems it's needed for me as well as for others:) Please, tell me if i forgot something to change.

**Comment by ascoders** [comment]
@wack17s Looks great! But we need to wait until `swipeDownThreshold` has been implemented in [react-native-image-zoom](https://github.com/ascoders/react-native-image-zoom).

**Comment by wack17s** [comment]
> @wack17s Looks great! But we need to wait until `swipeDownThreshold` has been implemented in [react-native-image-zoom](https://github.com/ascoders/react-native-image-zoom).

https://github.com/ascoders/react-native-image-zoom/blob/master/src/image-zoom/image-zoom.component.tsx#L473
Isn't it?

**Comment by ascoders** [comment]
@wack17s It's it~

**Pull request merged**
