### PR TITLE
Fixed typescript errors. updated package version

### PR DESCRIPTION
**Pull request by ShayanJavadi**
I don't seem to be getting the new version of the package when I do `npm install` this will fix that.

I fixed a few typescript errors causing issues and I also updated the package version.

### CODE REVIEW

**Comment by ShayanJavadi** [comment]
Actually this didn't seem to solve the problems. @ascoders do you happen to know why this is happening?
screen shot 2018-03-20 at 12 22 57 am

**Comment by ShayanJavadi** [comment]
disregard comment from earlier. this pr does in fact fix the issue.

**Comment by ascoders** [comment]
Thanks for fixing the problem, but I'm refactoring the swipeDown, and the old one has been deleted.

**Comment by ShayanJavadi** [comment]
@ascoders sounds good! when do you expect for it to be done?

**Comment by ascoders** [comment]
It's will be released the next few days. @ShayanJavadi

**Comment by ShayanJavadi** [comment]
@ascoders wonderful! thanks!

**Pull request closed without merging**
